### ISSUE TITLE
Undefined method `tcp' on Socket

### ISSUE THREAD

**Issue by YorickPeterse** [rubysl/rubysl-socket#11]
Originally submitted at https://github.com/rubinius/rubinius/issues/3510:

> @saizai:
>
> https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/transport/session.rb#L70 requires Socket.tcp.
> 
> This raises an error in rbx-2.5.8: 
> 
>     kernel/delta/kernel.rb:78:in `tcp (method_missing)'
> 
> See https://github.com/net-ssh/net-ssh/issues/276

**Comment by carlhoerberg** [comment]
The Ruby implementation of the method can be found here: https://github.com/ruby/ruby/blob/ruby_2_2/ext/socket/lib/socket.rb#L314

**Comment by carlhoerberg** [comment]
The Ruby implementation of the method can be found here: https://github.com/ruby/ruby/blob/ruby_2_2/ext/socket/lib/socket.rb#L314

**Comment by saizai** [comment]
Any plans for fixing this? It kills e.g. Capistrano.

**Comment by YorickPeterse** [comment]
@saizai You'll want to keep an eye on https://github.com/rubysl/rubysl-socket/pull/9. While originally meant to only add `Socket.ip_address_list` and Addrinfo, this PR has now become a full on refactor/update of the entire Socket library.

**Comment by saizai** [comment]
@YorickPeterse Fair. But could at least that part be pushed? It seems like that part is implemented, and pushing it would fix the Capistrano problem.

**Comment by YorickPeterse** [comment]
@saizai No. The current implementation doesn't work and quite a few things still have to be taken care of.

**Comment by brixen** [comment]
@YorickPeterse could you elaborate a bit, please? What is the least amount of work needed to get Socket.tcp to work so Capistrano will work?

**Comment by YorickPeterse** [comment]
@brixen See my comment here https://github.com/rubysl/rubysl-socket/pull/9#issuecomment-166267600

**Comment by YorickPeterse** [comment]
Fixed by https://github.com/rubysl/rubysl-socket/pull/9
