### ISSUE TITLE
Several 2.1.1 release specs hang on OSX

### ISSUE THREAD

**Issue by chuckremes** [rubysl/rubysl-socket#12]
I have identified several specs that hang on MRI 2.2.3 running against the latest rubysl-socket release (71d2a458c9d1981d).

Environment:
OSX 10.10.5
MRI 2.2.3

Command:
% cd rubysl-socket
% mspec spec

These specs hang:

*  https://github.com/rubysl/rubysl-socket/blob/2.0/spec/basicsocket/send_spec.rb#L112

*  https://github.com/rubysl/rubysl-socket/blob/2.0/spec/socket/accept_spec.rb#L14

*  https://github.com/rubysl/rubysl-socket/blob/2.0/spec/socket/accept_spec.rb#L20

*  https://github.com/rubysl/rubysl-socket/blob/2.0/spec/socket/connect_spec.rb#L38

*  https://github.com/rubysl/rubysl-socket/blob/2.0/spec/socket/sysaccept_spec.rb#L14

*  https://github.com/rubysl/rubysl-socket/blob/2.0/spec/socket/sysaccept_spec.rb#L20

**Comment by brixen** [comment]
Possibly related: https://github.com/rubysl/rubysl-socket/commit/ad14dbd

When introducing a `sleep()` or `Thread.pass` etc. resolves some issue, there is likely a race condition present. Just making the specs pass may give the impression of correctness (or "no obvious errors"), but that doesn't help in actual usage.

**Comment by chuckremes** [comment]
Papered over by commit ad14dbde28048bc58d22d9080b4952f7d64e4351 which introduces a short sleep. After all of the work to fix race conditions recently hard to know where to start to figure this one out. If this is a problem in practice, we can reliably reproduce this hang by removing the `sleep 0.01` to find the race.
