### ISSUE TITLE
License of specs in this project

### ISSUE THREAD

**Issue by eregon** [rubysl/rubysl-socket#15]
Hello,

I would like to integrate the specs you created in this project in ruby/spec.
This way, more Ruby implementations can use these specs easily to test the socket standard library.

I would like to keep this as simple as possible in terms of licenses.
ruby/spec is and has always been MIT: https://github.com/ruby/spec/blob/master/LICENSE
This project uses a BSD 3-clause license: https://github.com/rubysl/rubysl-socket/blob/2.0/LICENSE

@YorickPeterse @chuckremes @brixen Since I believe you are the 3 and only copyright holders of this project, would you agree to let me relicense those specs as MIT, and credit your work, e.g., in the README?

Or do you want that these specs remain licensed as BSD and not MIT?
This creates additional headaches as ruby/spec would then needs to say some parts of some files under `library/socket` are licensed under BSD and not MIT like the rest.

**Comment by brixen** [comment]
It's fine with me to relicense to MIT in ruby/spec.

**Comment by YorickPeterse** [comment]
I'm fine with this. The BSD 3-clause and MIT license are pretty much identical anyway, and I don't think anybody cares enough about the name "rubysl-socket" for the BSD name clause to matter.

**Comment by eregon** [comment]
Thank you guys, it is much appreciated.
And thank you for writing extensive `socket` specs!
